### ISSUE TITLE
How do servers advertise the operations/workflows they can perform?

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/OperationsAndWorkflows#11]
Servers may only implement a subset of operations, and some operations may only be exposed as mini-workflows. For example, a server may be able to do FILL + BIND, but not do FILL independently.

**Comment by patrickkwang** [comment]
First, this is not possible via modifications to the server OpenAPI Query component because of the need to group some operations together into these mini-workflows. JSON Schema does not provide a way to constrain an array to be a concatenation of specified arrays.

**Comment by patrickkwang** [comment]
Doing this via the x-trapi extension (or a new one) would be straightforward. For example:
```yml
x-trapi:
  version: 1.1.0
  implemented-workflows:
    - ["fill"]
    - ["bind", "complete_results"]
    - ["filter_kgraph_orphans"]
```
Indicating that the server can perform fill or filter_kgraph_orphans independently or as part of a larger workflow, but that bind and complete_results can only be performed together. So fill+bind+complete_results would be possible, but not fill+bind+filter_kraph_orphans.

**Comment by dkoslicki** [comment]
Re: lists
No more tuples of operations: if some ARA only does a combo of operations (eg. fill+bind), don’t advertise these as a tuple, but instead create a new operation for it. If you can do fill and bind individually, don’t create a new operation for it. Servers see operations as nondecomposable entities

**Comment by patrickkwang** [comment]
https://github.com/NCATSTranslator/translator_extensions/pull/7
For example:
```yml
x-trapi:
  version: 1.1.0
  operations:
    - "lookup"
    - "complete_results"
    - "filter_kgraph_orphans"
```
